apiVersion: v1
kind: Pod
metadata:
  name: dev-env
  labels:
    name: dev-env
spec:
  restartPolicy: OnFailure
  containers:
    - name: mariadb-dev-user-secrets
      image: sles12/mariadb:10.0
      command: ["/setup-mysql.sh"]
      env:
        - name: ENV
          value: development
      volumeMounts:
        - name: infra-secrets
          mountPath: /infra-secrets
        - name: mariadb-unix-socket
          mountPath: /var/run/mysql
        - name: setup-mysql
          mountPath: /setup-mysql.sh
    - name: mariadb-test-user-secrets
      image: sles12/mariadb:10.0
      command: ["/setup-mysql.sh"]
      env:
        - name: ENV
          value: test
      volumeMounts:
        - name: infra-secrets
          mountPath: /infra-secrets
        - name: mariadb-unix-socket
          mountPath: /var/run/mysql
        - name: setup-mysql
          mountPath: /setup-mysql.sh
  volumes:
    - name: mariadb-unix-socket
      hostPath:
        path: /var/run/mysql
    - name: infra-secrets
      hostPath:
        path: /var/lib/misc/infra-secrets
    - name: setup-mysql
      hostPath:
        path: /usr/share/caasp-container-manifests/setup/mysql/setup-mysql.sh
